### ISSUE TITLE
Random delay (3-9 sec.) when the Reset button is pressed

### ISSUE THREAD

**Issue by Ramsis-SNES** [mrehkopf/sd2snes#117]
Title says it all (firmware used: official v1.9.0). This happens both on unmodified and SuperCIC-enhanced consoles, regardless to the in-game hook setting. Edit: Using an old CRT, of course.

EDIT: Upon further inspection, it's not just the SA-1 games, it's _all_ games. Just try _Super Mario Kart_ ...

**Comment by mrehkopf** [comment]
It's probably the reset hook (for phase correction) waiting for the firmware to respond, which in the first seconds of game operation is now still busy with ROM CRC calculation to decide on partial SRAM monitoring.
Does this happen to a freshly booted game only or also when it's been running for a while?

**Comment by mrehkopf** [comment]
Closed due to lack of feedback, feel free to re-open or just reply with any new input. :)

**Comment by Ramsis-SNES** [comment]
Oops, sorry. No idea why I never got back to your question. :-( I can't test it right now but from memory, I don't think I observed any reset delay in v1.10.x, so no worries. ;-)
