### ISSUE TITLE
SuperCIC 1.13 Not working

### ISSUE THREAD

**Issue by LittleRainGames** [mrehkopf/sd2snes#132]
I've been trying to get it working for a couple days now.

My custom cart wasn't working, so I got an original cic from SMW to see if it was something else, but my cart started working after that.
I also tested the supercic in my SMW cart to no avail.

I just compiled v1.10, and my cic superchip is now working. 

I didn't test any versions between 1.10.3 and 1.10.0,
Also I'm using an NTSC console if that makes any difference, cant get console version at the moment, but can if you would like me to.
[Here is picture from my logic analyzer for v1.13](https://forums.nesdev.com/download/file.php?id=16431&mode=view)
It hangs after the first response.

Better take it off the SD2SNES website!

Edit: Since I have my SNES on the bench and it would only take a second I tested v1.10.2 and its also working.

**Comment by mrehkopf** [comment]
Hmm, that's interesting because there are no changes to supercic-key.asm between v1.10.2 and v1.10.3. I had a similar problem when prototyping SuperCIC on the MK3 PCBs but it was due to pull-ups I forgot to disable on the I/O pins of the ARM MCU connected to the CIC pins.

**Comment by LittleRainGames** [comment]
Hmm, well maybe its worth noting the v1.10.3 that wasn't working for me was downloaded from the SD2Snes website, while the other ones I compiled.

**Comment by mrehkopf** [comment]
I updated the precompiled hex archive at https://sd2snes.de/files/supercic.zip which is confirmed working so far. Feel free to re-open if you encounter any issues :)
