### ISSUE TITLE
NEC Upd77P25D and 77c25c rom progenitor

### ISSUE THREAD

**Issue by darleiv** [mrehkopf/sd2snes#136]
ould you have the dsp files 1 2 3 4 to use directly in the official mcu nec? I have some prehistoric necs of these stored here with uv light off all are from old traffic light terminals
. it would have to be the 10,240 byte bin starting the UPD77c25D file at the DATA address rom 2000h- until the end 27FFF
rom instruction would go up to 1FF but i don't know how to mount these rom to make it compatible with the nec official upd77d25d or upd77c25c. are there the original rom? no google, I don't have it

**Comment by mrehkopf** [comment]
Hi, that's very cool to know they have been used in traffic light controls! I am not sure which would be the correct endianness to program the chips, but dumps are available here: http://www.caitsith2.com/snes/dsp/
The dump files are 8192 bytes. Instruction ROM data is at 0000-17FF, Data ROM from 1800-1FFF inside the files. You might need to pad them out if your programming tools require different addresses.
