### ISSUE TITLE
[v1.11.0b1] Small blemish in "Favorite games" menu

### ISSUE THREAD

**Issue by Ramsis-SNES** [mrehkopf/sd2snes#156]
If you press B to go back from here (image taken from https://github.com/mrehkopf/sd2snes/pull/134) ...

![IMG_20200222_150006](https://user-images.githubusercontent.com/16519229/75093687-4e8b0880-5584-11ea-9535-a65a9b42408f.jpg)

... the menu will flicker slightly, and the selection bar will be placed on the topmost entry in the favorite games list instead on the one the context menu was opened for. (Normally, all sub-menus close without any flickering, and the selection bar is placed on the previously selected element.)

Not a big deal at all, I know, but it just caught my eye. ;-)

**Comment by Ramsis-SNES** [comment]
Awww, I was hoping for a fix for this in the final version. :p Oh well. ;-)

**Comment by freelancer42** [comment]
This one's probably my fault. I implemented the favorites feature after digging through the SD2SNES code without any prior knowledge of how it worked, so I might've picked the wrong subroutine for something. Sorry :)
I'm glad people find it useful though!

**Comment by mrehkopf** [comment]
Heh, forgot about it. I was really too focused on getting the critical stuff to work on Rev.D but I think it was necessary...
Will fix it for 1.11.1 ;)

**Comment by mrehkopf** [comment]
Please give it a try :) [menu.zip](https://github.com/mrehkopf/sd2snes/files/10778196/menu.zip)

**Comment by Ramsis-SNES** [comment]
> Please give it a try :) [menu.zip](https://github.com/mrehkopf/sd2snes/files/10778196/menu.zip)

Works just fine now, thanks a lot, ikari! :D
