### ISSUE TITLE
MSU1 games with motion video glitches on 1.11.0b1

### ISSUE THREAD

**Issue by kimbapslice** [mrehkopf/sd2snes#161]
MSU1 games with motion video glitches on 1.11.0b1 and not on 1.10.3. I am using 2/1/3 snes (ntsc/usa). Switch back to 1.10.3 works fine.

Mega Man IV intro's
Akira Trailer
Super Road Blaster
etc

Tried it with PNY 16gb microsd class 10 and a Samsung Evo 32GB micro sd.

**Comment by kimbapslice** [comment]
I tested Super Road Blaster today on 3 fully working (as far as I can tell) USA snes with configuration 2/1/3 snes (ntsc/usa). I have disabled all in-game menu and gamesaves. Snes burn-in test v1.03 reports all pass on all 3 systems.

Results for Super Road Blaster with 1.11.0b1 video glitches on all 3 snes.
Results for Super Road Blaster with 1.10.3 NO video glitches on all 3 snes.

My sd2snes is an old official E1b revision that I have upgraded to revision H.

**Comment by manwithouties** [comment]
I know this post is old... well, I'm experiencing the same issue. Have you found a solution?
I don't want to keep using 1.10.3 because I love the save state and SGB features.

**Comment by kimbapslice** [comment]
Ok, so here's an update on further testing. I recently acquired a snes 1chip-01 and snes mini/jr. Both the 1chip-01 and snes mini/jr report 2/1/3 configuration. Both are NTSC/USA revisions.

Super Road Blaster with 1.11.0b1 on snes 1chip-01 = video glitches
Super Road Blaster with 1.11.0b1 on **snes mini/jr = normal, correct video**

New findings!

**Comment by manwithouties** [comment]
@kimbapslice Thanks for your reply and testing! So, no easy fix! I tried manipulating some files on the sd2snes folder with no success. Anyway, it's a firmware issue and needs a fix... let's hope developers can solve it on next update. Meanwhile I'm using two SD cards, one with 1.11.0 and other one with 1.10.3.

**Comment by mrehkopf** [comment]
SNES mini/jr and 1chip are technically identical. Could either of you provide a recording of the glitches?
Do the glitches recover at all on the MSU1 video demos (e.g. Akira)?
Are the glitches still present in the 1.11.0 final? Can you let the SD card access time measurement complete on the System Information screen and post the results?

**Comment by mrehkopf** [comment]
Thank you 🙇‍♂️ So far I've been unable to reproduce the issue here. The only thing that caused intermittent glitches was a very slow card with a max access time of 11ms... However there seems to be an issue with bus timing on 1.11.0 (#204, #184), maybe the underlying cause is similar.
Can you run Illusion of Gaia and check for flickering of the Nintendo/Enix logos and corrupted graphics?

**Comment by kimbapslice** [comment]
Hello,

So today I tested the 1.11.0 release with 2 snes (1chip-01, and not a 1chip), 2 snes jr. All four systems are 2/1/3, running composite video. First tested with my sd2snes upgraded to 1.11.0

Results on 1.11.0:
Snes (not 1chip, stock), snes 1chip-01(brightness fix+vertical band fix) = MSU1 videos GLITCH
Snes JR (stock): MSU1 works
Snes JR (rgb mod, brightness fix): MSU1 works

Results on firmware 1.10.3
MSU1 videos work on all consoles

I hope this helps!

Thank you so much for your work!

![00_Card_Index](https://user-images.githubusercontent.com/58018661/223560149-7d61297f-06f7-4d8e-a3e1-0af09a2b015f.jpg)
![01_PNY16Class10](https://user-images.githubusercontent.com/58018661/223560182-15f11e7e-018a-47bb-aa38-f6eebfb2abad.jpg)
![02_SandiskUltra64_class10](https://user-images.githubusercontent.com/58018661/223560283-22f5a8ca-e2d9-493e-8849-6e3c4352c28d.jpg)
![03_Samsung256EvoU3](https://user-images.githubusercontent.com/58018661/223560411-7e18add5-6744-4e7c-b27a-2ff24861d85c.jpg)
![04_Samsung64ProPlusU3](https://user-images.githubusercontent.com/58018661/223560464-3b723e69-3db3-463e-b704-6d979ad07b05.jpg)
![05_PNY32Class10SD](https://user-images.githubusercontent.com/58018661/223560542-3d20fe84-5084-47a1-84da-53fdfeda263e.jpg)
![06_PNY64U3](https://user-images.githubusercontent.com/58018661/223560615-1c3dfa2c-a270-458a-9aa4-0083fbb3c7ab.jpg)

https://user-images.githubusercontent.com/58018661/223561377-7df4587b-527a-4802-884b-4cf5c32f426f.mp4


https://user-images.githubusercontent.com/58018661/223561402-c653811a-9a31-4b3b-8d7f-ea301367dafa.mp4

**Comment by mrehkopf** [comment]
Thanks! Looks like it's missing one byte of data pointer increment at the beginning of each DMA transfer... will need to check how recent changes might have caused that.

**Comment by mrehkopf** [comment]
Can you try this (only for OG sd2snes)? Just replace the fpga_base.bit in your sd2snes folder with the one from the zip file.
It's not a final fix, just changed the way MSU address is incremented to close in on the issue.
[fpga_base_msu1_address_inc.zip](https://github.com/mrehkopf/sd2snes/files/10925532/fpga_base_msu1_address_inc.zip)

**Comment by kimbapslice** [comment]
Wonderful news! The fpga_base.bit did the trick and now firmware 1.11.0 works on all of the 4 snes tested. I was able to run through the entire trailer of Akira, Super Road Blaster works. Thank you!

**Comment by mrehkopf** [comment]
Ah that's good to know, thanks! I'd like to try different approaches (due to interaction with other issues) so would be great if you could try maybe 1-2 other fpga_base.bit files that I'm going to attach here :)

**Comment by kimbapslice** [comment]
Yes, I can do that and report back. Thanks!

**Comment by mrehkopf** [comment]
Awesome! Here is another one: 
[fpga_base_new_address_sampling.zip](https://github.com/mrehkopf/sd2snes/files/10951891/fpga_base_new_address_sampling.zip)

**Comment by kimbapslice** [comment]
The new address sampling returned to the only snes working was the snes jr systems.

1chip-01 and non-1chip = msu1 video glitches
snes jr stock = works


https://user-images.githubusercontent.com/58018661/224580554-1dd25cd5-4b95-45da-b539-1e1f1d14efdb.mp4


https://user-images.githubusercontent.com/58018661/224580555-5824fce1-d974-4d07-aea6-0ff5a6b03f56.mp4


https://user-images.githubusercontent.com/58018661/224580556-9fb253a7-6fc8-43ac-96c6-714ec939d530.mp4

**Comment by mrehkopf** [comment]
Another try 😅 
[fpga_base_new_address_sampling2.zip](https://github.com/mrehkopf/sd2snes/files/10952695/fpga_base_new_address_sampling2.zip)

**Comment by kimbapslice** [comment]
Sampling2 results:

non1chip and 1chip-01: glitches, but sometimes shows briefly correctly the first 1-5 seconds of akira/music videos. Super Road Blaster glitches much less but it's still messes up on and off.

snes jr: works perfectly

**Comment by mrehkopf** [comment]
Yet another try 🙏
[fpga_base_new_address_sampling3.zip](https://github.com/mrehkopf/sd2snes/files/10955548/fpga_base_new_address_sampling3.zip)
If this doesn't work I'll probably stick with the MSU specific fix for now.

**Comment by kimbapslice** [comment]
Sampling3 results:

non1chip and 1chip-01: glitches
snes jr: works perfectly

**Comment by mrehkopf** [comment]
OK, went with the first approach for the time being. Thanks for all the testing :) v1.11.1 is around the corner, feel free to re-open the issue if any issues persist.
