### ISSUE TITLE
[v1.11.0] Super Mario Kart hangs at the Nintendo logo just after launching the game.

### ISSUE THREAD

**Issue by Rakutenka** [mrehkopf/sd2snes#188]
Super Mario Kart hangs at the Nintendo logo just after launching the game. This game worked fine in v.1.10.0, but after doing a fresh install of the new firmware the game doesn't work anymore. I tried turning off "in-game hooks," but this didn't change anything. I've tried several other games without issue. So far only Super Mario Kart is having this issue for me.

Playing this on a SHVC-CPU-01with a SNS-CPU-GPM-01/02 CPU

**Comment by mrehkopf** [comment]
Hi! Sounds like the DSP files are missing. (dsp1b.bin etc.) Can you check if you have them in your fresh sd2snes folder?

**Comment by Rakutenka** [comment]
I'm a dummy. It was missing all the .bin files. I added them all back and now it works. Thanks.
