### ISSUE TITLE
"Super Bomberman" (BS-X) Crash on bootup.

### ISSUE THREAD

**Issue by KiddoCabbusses** [mrehkopf/sd2snes#19]
Even though this is just a straight redux of the original Super Bomberman with no discernible change from the original SNES release, which I think works fine on the sdsnes, no? ... For some reason the dump of Super Bomberman for the Satellaview crashes on sd2snes after selecting it from the BS-X Memory Pack loader.

**Comment by devinacker** [comment]
I just re-checked this with 0.1.7 pre4 and it loads fine. (and looking back at old release notes, it seems this was fixed back in pre2, actually.)

**Comment by mrehkopf** [comment]
Thanks, forgot to close it :)
