### ISSUE TITLE
[v1.11.0] Final Fantasy 3/6 - Black/corrupt equip screen with or without in-game hooks

### ISSUE THREAD

**Issue by jami3rez** [mrehkopf/sd2snes#191]
When accessing menus the screen is mostly black and is typically missing information. Sometimes random garbage characters are in the place of letters and numbers.

![3D814F8C-EBE5-486B-B077-EB860FCE58C3](https://user-images.githubusercontent.com/48032389/216757687-d263d5c6-9cc6-438b-8833-b85bdf3e6044.jpeg)

This happens irrespective of whether in-game hooks are turned on or off.

No other games have exhibited any problems with my SD2SNES cart and my SNES console passed all suggested testing suites I have thrown at it.

This problem persists across all firmware I have tried and multiple different ROMs, both official and those with hacked ‘fixes’.

**Comment by mrehkopf** [comment]
Thanks for reporting; this increases the number of reports with this issue to three, so there seems to be some consistency to it. So far I haven't been able to reproduce the issue myself...
Does it happen every time you enter the equip menu, or just sometimes? Is it possible to reproduce (for me) when entering the equip menu even in the intro sequence (when Terra is still named "?????")?
Finally, what type of SNES are you using, and do you have 1CHIP Transient Fixes or Brightness Limit enabled in the menu?

**Comment by jami3rez** [comment]
Hi, thanks for the replies.

I am not using a PAL, non-1CHIP console.

These problems occur with every single option in the SD2SNES Config menu disabled, that includes Save States, Brightness Limit etc. They occur every time I access the Item, Skills, Equip and Relic menus without fail. Status, Config and Save display normally.

I have recreated the issue from a new game with Terra named ????? below.

![2ECEF894-041F-4CCC-B000-B43F44CF3DD8](https://user-images.githubusercontent.com/48032389/216812937-6f3dc216-dd33-4f89-9936-1bb4fec3dc78.jpeg)
![2B52E45A-E26B-4099-8D8F-AAE20FC57C85](https://user-images.githubusercontent.com/48032389/216812942-73975269-ce3f-48d0-8434-1d82ee607cb9.jpeg)
![3576E899-19C7-42BB-A748-8C2A77262304](https://user-images.githubusercontent.com/48032389/216812947-b91e74fb-6934-4e20-965f-78f579e6269e.jpeg)

The following are from a save game about an hour in. This is as far as I have played.

![F7A606E9-FA7A-4B17-B46D-ABA2C97295EE](https://user-images.githubusercontent.com/48032389/216813009-8045429b-fd84-4085-873b-73065fac1c9a.jpeg)
![3DF5EF48-3C81-4565-9AA5-E52AFCCFB7B7](https://user-images.githubusercontent.com/48032389/216813013-2a1ec8b6-c23d-4098-a536-cfdab5b4911b.jpeg)
![7A0F5C5E-61A7-4E72-9893-20CC7CB9401D](https://user-images.githubusercontent.com/48032389/216813020-9ddca27b-6567-4ea3-9286-018e58e5852c.jpeg)
![C8C14F90-3D53-40D1-ADE1-CF10A6892BF4](https://user-images.githubusercontent.com/48032389/216813029-acb6fbaf-bb38-4ea1-bc74-31258f9f30b0.jpeg)
![7AF2BCA4-7471-495E-9DFA-3566017F7367](https://user-images.githubusercontent.com/48032389/216813002-2214ea99-6ea4-4d4f-afa9-94920f22c0de.jpeg)
![07D654F1-7AA3-48D3-97B7-AC9B77288779](https://user-images.githubusercontent.com/48032389/216812986-4a78fd5b-d6c0-47ce-a76a-476fc605ca13.jpeg)
![1A58BB48-EBB7-4DF4-BA02-2E910206AA40](https://user-images.githubusercontent.com/48032389/216812994-f6b9fcb7-22d7-4bd4-a709-5d8e7f8fc22a.jpeg)

**Comment by Ramsis-SNES** [comment]
Possibly a 50/60 Hz issue, this is known even with an original cart.

**Comment by mrehkopf** [comment]
Oh dear, you're right - it's been such a long time that I had completely forgotten about this issue. Yes, it's indeed a game "bug" when run at 50Hz on a PAL console.

**Comment by jami3rez** [comment]
> Possibly a 50/60 Hz issue, this is known to happen even with an original cart.
> 
> Edit 2: Try this: [FF6 PAL fix](https://www.romhacking.net/hacks/106/)

Fantastic stuff! This does seem to have done the trick as the menus I mentioned do display normally now.

Couple of caveats. 

1. On the intro sequence of the mechs walking through the snow the ground looks like a chess board. Alternating big black squares. Otherwise fine. Could be an issue with the patched ROM I guess, but not a massive issue.
2. With in-game hooks enabled the overworld map flickers constantly. The menus however continue to display fine.

Thanks again for the help.

**Comment by mrehkopf** [comment]
Hm! I don't know how the patch works but maybe it just "wastes" cycles to mimic the NTSC timing, up to the point that not enough are left for the in-game hook - in that case it might be possible to loosen the timing of the patch itself a little.

**Comment by Ramsis-SNES** [comment]
>     1. On the intro sequence of the mechs walking through the snow the ground looks like a chess board. Alternating big black squares. Otherwise fine. Could be an issue with the patched ROM I guess, but not a massive issue.
Definitely neither an issue with the PAL fix patch nor the sd2snes. Be sure to try the patch on a fresh ROM to rule out any hack incompatibilities. ;-)

> Hm! I don't know how the patch works but maybe it just "wastes" cycles to mimic the NTSC timing, up to the point that not enough are left for the in-game hook - in that case it might be possible to loosen the timing of the patch itself a little.

From my memory, all the PAL fix patch does is re-enable one of the BGs in the menu, and have the sound driver wait for the game engine to catch up in the ending sequence so it won't crash with a black screen. I could be mistaken though ...

**Comment by StrikerMan780** [comment]
I get this corruption (but worse) in an NTSC FF3/6 ROM. So, I don't think it's a pal-specific issue. I can't seem to remedy it aside from turning off hooks.
