### ISSUE TITLE
weird SD2SNES clone. Help needed

### ISSUE THREAD

**Issue by way5** [mrehkopf/sd2snes#259]
Hello everyone! 
I am new to this topic so I'd appreciate an expert opinion. A couple of weeks ago I've acquired chinese SD2SNES (which you may see on the photo). 

![sd2snes](https://github.com/user-attachments/assets/015c9353-60f4-49b2-b6b4-0c6c7e40ddab)

It seems to be well made at first glance, however I immediately started having issues with that.

Input data:
- original SFC (US NTSC). The board is recapped recently.
- tested with different PSU 9V(2A), 12V(2A)
- tested with firmwares 1.10.3 (factory), 1.10.3, 1.10.3 (by furious), 1.11.0 (latest, no video)
- tested with various SD cards (32-128GB). the results are the same

System information:

![sys_info](https://github.com/user-attachments/assets/15a6fca1-b9a7-4609-b2f1-6f6d0328cd65)

Issues:
1. The most annoying issues is that I am unable to open directories. Once I am trying to open one the cursor jumps back to the first row in the list. So I've moved sfc roms into SD card root to be able to start them. However...
2. Some games work fine, but most of them having issues at the very beginning of execution or shortly after starting the game. Mostly it just freezes. Sometimes I am able to do IGR though, which returns me to game intro.
3. I am not able to change settings via SD2SNES interface. It's possible to edit `config` directly by hand, but I feel there is nothing changing afterwards. Settings are not applied or having no effect.
4. It says `CIC state: Original or no CIC` which doesn't explain a thing to me.
5. Firmware version 1.11.0 gives me no meaningful video image (see image below). I've tried to follow the steps in this [report](https://github.com/mrehkopf/sd2snes/issues/184), but no luck.

![fw 1 11 0](https://github.com/user-attachments/assets/5b71ff77-8eb9-44b1-8434-52f5b79da068)

I've done some reading on Internet about similar issues and possible solutions, but it is not becomes clear to me what is going on to this SD2SNES.

------------- 

**Is there any possible solution of the product is faulty?** 
Please share your opinion.

~Thanks!

------------

![back](https://github.com/user-attachments/assets/65f9c429-df48-4f9a-be98-a627a0bd51cb)

**Comment by mrehkopf** [comment]
Oh, that's an interesting device I haven't seen before. For issues I think it would be best to contact the dealer/manufacturer :)

**Comment by Romain80200** [comment]
Hello, it look like 2 components are missing, R301 and Q301.

**Comment by way5** [comment]
> Oh, that's an interesting device I haven't seen before. For issues I think it would be best to contact the dealer/manufacturer :)

I guess this may be sort of a taunt. :) Alright, as I said I am newbie to SFC stuffs. 
I have seen this devices on Internet, and the very first time it is in my hands. And despite its well designed look it seems to be in very beta stage yet, am I correct?
The manufacturer/seller gives no support on that, the only way is to return this device, but I wonder if this is an issue of my SFC maybe, or something else.

Thanks

**Comment by way5** [comment]
> Hello, it look like 2 components are missing, R301 and Q301.

Thanks! Is there any schematics which I could refer to?

**Comment by Ramsis-SNES** [comment]
Assuming it's not a hardware fault (which is likely, unfortunately), how did you format your SD cards? (Hint: Don't use tools like Rufus and GPT mode, as it will mess things up.)

**Comment by way5** [comment]
> Assuming it's not a hardware fault (which is likely, unfortunately), how did you format your SD cards? (Hint: Don't use tools like Rufus and GPT mode, as it will mess things up.)

@Ramsis-SNES, Thank you for sharing your opinion.
Cards were formatted with FAT32 format. I had no issues with that method earlier. Last thing to blame is SD card I think. 
The problem also is that there is no  structured info on this devices what so ever, I was expecting to find schematics at least for earlier versions.
No data on this sort of problems either. Maybe not many people are using it though.

What does this mean when 'no CIC detected'?

**Comment by Ramsis-SNES** [comment]
> The problem also is that there is no structured info on this devices what so ever, I was expecting to find schematics at least for earlier versions.

Those have been up [on this very GitHub repository](https://github.com/mrehkopf/sd2snes/tree/develop/pcb/kicad) for 8+ years.

> What does this mean when 'no CIC detected'?

Don't worry about it, it's perfectly normal with an unmodded console; otherwise, it would say, "SuperCIC-enhanced." :-)

**Comment by way5** [comment]
@Ramsis-SNES , darn, I am outdated! :) thanks for the information

Which mod do you mention for CIC?

**Comment by way5** [comment]
@Ramsis-SNES , so the board on the photo I've posted is basically somewhat "enhanced" version of the official SD2SNES? And schematics in this repo is the only latest updated version for oficial working device?
That was not clear in the beginning. I thought the device version I purchase is the latest upgraded community version.

Which mod do you mention for CIC?

**Comment by way5** [comment]
@Ramsis-SNES , so the board on the photo I've posted is basically somewhat "enhanced" version of the official SD2SNES? And schematics in this repo is the only latest updated version for oficial working device?

That was not clear in the beginning. I thought the device version I purchase is the latest upgraded community version and I just don't know where to find the correct schematics.

**Comment by Ramsis-SNES** [comment]
> @Ramsis-SNES , so the board on the photo I've posted is basically somewhat "enhanced" version of the official SD2SNES? And schematics in this repo is the only latest updated version for oficial working device?

I honestly don't know the answer to either of those questions.

What you need to understand though is this: The sd2snes/FXpak is an open source project. As such, anyone can make changes to the design, and offer their product commercially. If you as a buyer want the real thing, you need to make sure to only buy from a reputable seller in order to receive a product that works as advertised.

From what you describe, your cart is very likely faulty, and even if it was fully working, it probably isn't exactly built to spec anyway. If I was in your position, I'd return the non-working item, get a refund from the seller, and invest my money in the real deal. :-)

**Comment by DCSpecial** [comment]
> No data on this sort of problems either. Maybe not many people are using it though.

FXPak Pro (formely named sd2SNES) is probably _THE_ go to SNES flashcart -> but i would recommend using a genuine one  produced by krikkz instead of chinese "knock offs" based on old (open source) designs

**Comment by TharathielCB** [comment]
Go and buy one by krikkz. In that case ikari (mrehkopf) would get some money for his great work. I would not give any support on a very bad Chinese mock off if I were the developer ;)

**Comment by Romain80200** [comment]
R343 is also missing.
I don't know if it matter.

**Comment by way5** [comment]
@Ramsis-SNES, really appreciate your opinion on that matter. 
I've actually returned this device.
Issue solved.

Thanks
