### ISSUE TITLE
SUPER MARIO RPG FREEZE BUT SOUND KEEPS PLAYING ON SD2SNES REV X2 AND CONSOLE 2/1/3

### ISSUE THREAD

**Issue by r0g1nh0** [mrehkopf/sd2snes#261]
My current console is 2/1/3 and i have a SD2SNES rev X2. I tested on version 1.10.3 and 1.11.0 with and without the issue 186 patch.

I would really like to play Super Mario RPG, but this game crashes and freezes many times before passing the first gate of the game. And sometimes it runs until the first battle with Bowser and freezes, leaving only the sound playing in the background.

**Comment by mrehkopf** [comment]
Hi, sorry I can't support or fix issues with Chinese clones. They seem to mess up in a variety of ways that I can neither analyze nor account for all of them in the firmware. Best bet is asking for support from your vendor/manufacturer.
