### ISSUE TITLE
Feature request: Favorites list

### ISSUE THREAD

**Issue by magu** [mrehkopf/sd2snes#31]
It would be awesome to have the possibility to flag certain roms as favorites, and then to be able to filter by that. This would significantly help when browsing a large rom collection, so you could just flag what you for example currently play to find it quickly in the list instead of moving stuff around physically on the file system to a "currently playing" or favorites folder.

Easy way to implement this UI-wise would be to for example toggle favorite status with one button in the file browser, and then have another button switch between the file browser and a sorted list of favorites. Favorite status could be indicated with anything subtile in the file browser, like a small asterisk next to rom size, or anything similar. Toggling favorite status wile browsing the favorites list would also remove the rom from the list instantaneously.

(By the way, the sd2snes is awesome! Got mine yesterday and couldn't be more satisfied.)

**Comment by mrehkopf** [comment]
Integrated in v1.11.0b1 :)
