### ISSUE TITLE
Feature request: Force region of sd2snes menu

### ISSUE THREAD

**Issue by magu** [mrehkopf/sd2snes#32]
My SNES is a PAL one with SuperCIC and IGR installed. The SuperCIC is wired with REG_TIMEOUT set to high, and i normally use it with force 60 Hz. Since the sd2snes detects the SNES as being a PAL one (I assume) it identifies as a PAL game, thus making the timeout trigger and show the sd2snes menu in 50 Hz for ~9 seconds on every boot.

This is quite annoying, and it would be awesome to be able to force the sd2snes menu to identify as a particular region, through a menu item or the like. (I could of course open the SNES up and rewire REG_TIMEOUT to low, but I quite like it this way when playing original cassettes.)

I assume this is sort of related to "supports software 50/60Hz switching on SuperCIC enhanced consoles only (to be performed by sd2snes firmware, not yet implemented there)", and perhaps will get added when that is implemented.

**Comment by magu** [comment]
Am I correct in noting that this is now implemented in 0.1.7pre4? I've set the config file to force 60 Hz/60 Hz, and never see the abominable 50 Hz stripes any more.

**Comment by mrehkopf** [comment]
Yes, if you also set PairModeAllowed to true it will do that exactly. ;)

**Comment by magu** [comment]
Yup, I had done that. This makes me happy, and my 5 years old son less confused. Thanks a bunch!

**Comment by mrehkopf** [comment]
Implemented and integrated in v0.1.7b
