### ISSUE TITLE
"Error 09" when trying to boot BS-X titles other than the first on the list

### ISSUE THREAD

**Issue by redeemer665** [mrehkopf/sd2snes#35]
The new 0.1.5 firmware seems to be having trouble with BS-X data packs with more than one software title. More specifically, only the first title of a data pack will boot correctly, all others will bring up the "Error 09" screen. Both PSRAM and FLASH-configured games are behaving the same.

**Comment by devinacker** [comment]
Gave this a try on 0.1.7 pre4 and it seems to work well now. I don't have a lot of data packs with multiple titles, but I was able to use [this one](http://superfamicom.org/blog/2013/09/2roms1dump-or-2dumps1rom-or-aw-the-heck-with-it-some-new-picross-for-you/) and load both of the titles on ChronoMoogle's dump successfully.

I don't know if @KiddoCabbusses ever tried that dump again, but it seems to work fine in the latest sd2snes firmware as well as the latest builds of bsnes-plus with help from LuigiBlood. Some other problematic titles (like BS Fuurai no Shiren) still have trouble booting though.
