### ISSUE TITLE
Shin Megami Tensei II.

### ISSUE THREAD

**Issue by ceramiclion** [mrehkopf/sd2snes#56]
Shin Megami Tensei II on SD2SNES flickers on the world map walking near the buildings. This issue happens whether the game is patched for english or a clean rom. The patching however seems to make the flicker get worst.
It does not seem to flicker on any emulator however.
Thank you.

**Comment by mrehkopf** [comment]
while in-game can you try pushing L+R+Start+Y and see if the flicker goes away?

**Comment by ramapcsx2** [comment]
If this ever was an issue, it appears to be fixed in 0.1.7.d :)

**Comment by devinacker** [comment]
Probably was an issue with ingame hooks like @mrehkopf suggested, then.

**Comment by mrehkopf** [comment]
Looks like I had completely forgotten about this issue. Good to hear that the latest hook improvements fixed it. :)
