### ISSUE TITLE
Save state support

### ISSUE THREAD

**Issue by Skarsnik** [mrehkopf/sd2snes#57]
I could be nice to have a save state support.

Some people hacked game like Zelda 3 and super metroid to add save state support by copying the ram in the sram. (Using a second controller to load/save). Maybe sd2snes could have something similar to this :)

**Comment by xadox-1st** [comment]
That would be a great feature.

**Comment by hyrulebr** [comment]
Something like mega everdrive would be very nice!

**Comment by ramapcsx2** [comment]
Is everyone is aware that on the SNES, a save state function can not include the APU state?
This will lead to sound being off or weird most of the time, and in some cases it will break the game.
Most of the time though, the ship will correct itself on a level load.
A savestate feature would be awesome, even with this limitation :)

**Comment by gnadenlos** [comment]
usb2snes + savestate2snes work quite well, but they require an active USB connection to patch the games in memory every single time we want to use the feature.

A solution like that without the requirement of an USB connection would be a great start and much better than having no savestate support.

Even if you only integrate the existing code from redguy directly in the SD2SNES firmware and menu would be a nice improvement and give us quicksave / quickload (Select + R & Select + L) in a lot of games without the need for USB connections.

**Comment by mrehkopf** [comment]
Savestates have now been integrated with the current firmware beta release (v1.11.0b1), with some compatibility improvements (and still room for improvement of course).
