### ISSUE TITLE
Glitches in Metal Combat

### ISSUE THREAD

**Issue by LoganA95** [mrehkopf/sd2snes#73]
I've used Firmware v0.1.6 and no problems with this but when I upgraded to v0.1.7 I noticed glitches on the intro, title screen and in-game (missing/glitched objects). It even happens when I turn off in-game hook and buttons. I have 2 SNESes and the problem happens on both.
http://i1360.photobucket.com/albums/r655/TheSonicFanDude/0420160227_zpslow0zltq.jpg

**Comment by mrehkopf** [comment]
Thanks, I'll take a look.

**Comment by mrehkopf** [comment]
Got it, I removed the OBC1 feature enable flag from the ROM identification code (because a OBC1 specific FPGA configuration is loaded anyway) but did not change the FPGA code to reflect the change - as a result the OBC1 is always disabled, resulting in (almost) no sprites.
