### ISSUE TITLE
USB Mini Type B THT in BOM file, but revF appears to be SMD/SMT

### ISSUE THREAD

**Issue by zeruel85** [mrehkopf/sd2snes#74]
Reading the BOM file in revF directory, it appears that we have to use a Mini USB Type B Through-Hole Technology, but viewing the design in KiCad or in Gerber View, it appears to be a SMD/SMT one.

**Comment by ccoulton** [comment]
Also the BOM has a obsolete part that has no optional part, it's the sram, digikey 557-1444-1-ND.
