### ISSUE TITLE
Random characters flashing on the System Information screen

### ISSUE THREAD

**Issue by Ramsis-SNES** [mrehkopf/sd2snes#75]
Go to Main Menu/Settings, wait 'til it's finished calculating disk space and measuring SD access time, and then just stare at your TV without blinking. ;)
![sdinfo](https://cloud.githubusercontent.com/assets/11965591/15340279/e85a6b2e-1c88-11e6-8f02-29c86df058f0.jpg)

Tested with a 2-PPU-SNES (PAL, SuperCIC-modded, 50 and 60 Hz mode).

**Comment by mrehkopf** [comment]
A little race condition between the string creation (MCU side) and printing (SNES side). Fixed by reordering the string creation.
