### ISSUE TITLE
Issues when backing out of the SPC player

### ISSUE THREAD

**Issue by SwordlessWarrior** [mrehkopf/sd2snes#81]
I noticed a problem that happens when you select a SPC file when a file with a name that's too big to fit on the screen is scrolling.

This is how it looks before it starts scrolling:
![downsized_0725161647](https://cloud.githubusercontent.com/assets/20649844/17117171/8aa32fc2-52aa-11e6-9daf-93dc402b91a6.jpg)

and this is how it looks when I select the file after it scrolls and back out:
![downsized_0725161701](https://cloud.githubusercontent.com/assets/20649844/17117410/7ab0fd00-52ab-11e6-9600-a2d5b5592c59.jpg)

But when I scroll down the list or go to another folder it fixes itself.

**Comment by mrehkopf** [comment]
Heh, it scrolls all file names because the scroll displacement isn't reset before going back to drawing the file list.

**Comment by mrehkopf** [comment]
Where did you get the SPC packages with the nice file names? I can only find "thg-1-01.spc", "thg-1-02.spc" etc.

**Comment by mrehkopf** [comment]
Nevermind, found nice archives at http://spc.joshw.info/ ;)

**Comment by mrehkopf** [comment]
Fixed in c85d302

**Comment by mrehkopf** [comment]
Integrated in v0.1.7d
