### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by marvelus10** [mrehkopf/sd2snes#86]
A one time boot of a rom image, select rom in menu - power off - power on and rom is booted instead of SD2SNES menu. This would be beneficial for loading test roms on broken consoles that will not load games or SD2SNES for that matter. You could select test rom for one time boot and after power off place SD2SNES in broken console and power on.

**Comment by tandraschko** [comment]
Sounds like https://github.com/mrehkopf/sd2snes/issues/85
