### ISSUE TITLE
Tales of Phantasia crashes in sound menu on 0.1.7e

### ISSUE THREAD

**Issue by dododub** [mrehkopf/sd2snes#89]
The sound menu functions for a few seconds but crashes no matter what you do. It happens on original hardware (Super Famicom) and on a Super Nt. Happens both in original Japanese rom and translated rom.

**Comment by mrehkopf** [comment]
The sound menu does not like the in-game hook very much. It should work if you disable it.

**Comment by dododub** [comment]
Disabling the in-game hook indeed fixes the problem.
