### ISSUE TITLE
File List Word-Wrap

### ISSUE THREAD

**Issue by tjstogy** [mrehkopf/sd2snes#97]
Similar to the Mega Everdrive- it would be nice if when scrolling past the bottom of a list brings you back to the top of the list, and vice-versa.

**Comment by mrehkopf** [comment]
You can jump to top/bottom of the list using the L/R shoulder buttons. Is that sufficient?

**Comment by Ramsis-SNES** [comment]
@mrehkopf Totally, IMHO. :D
